# Generated by Django 2.1.3 on 2018-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='model_pic',
            field=models.ImageField(default='pic/download.jpg', upload_to='pic/'),
        ),
    ]
