# Generated by Django 2.1.3 on 2018-11-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_model_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='pic/download.jpg', upload_to='pic/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='model_pic',
        ),
    ]
